name: plsdb
channels:
    - defaults
    - conda-forge
    - bioconda
dependencies:
    - conda-forge:biopython==1.73
    - conda-forge:numpy==1.19.4
    - conda-forge:pandas==0.24.2
    - conda-forge:tqdm==4.32.1
    - conda-forge:umap-learn==0.4.6
    - bioconda:mlst==2.19.0
    - bioconda:abricate==1.0.1
    - bioconda:snakemake==5.5.0
    - conda-forge:requests==2.22.0
    - conda-forge:geocoder==1.38.1
    - bioconda:perl-net-ssleay==1.88
    - bioconda:perl-libwww-perl==6.36
    - bioconda:perl-lwp-protocol-https==6.07
    - r-base==3.6.1
    - r-testit==0.12 
    - r-argparse==2.0.3
    - r-ggplot2==3.3.2 
    - r-scales==1.0.0
    - r-maps==3.3.0
    - r-dplyr
    - entrez-direct==13.9 
