name: plsdb
channels:
    - bioconda
    - conda-forge
    - r
dependencies:
    - python==3.5.6
    - conda-forge:biopython=1.68
    - conda-forge:numpy=1.15.2
    - conda-forge:pandas=0.23.4
    - conda-forge:tqdm=4.64.0
    - conda-forge:umap-learn=0.3.2
    - bioconda:mlst=2.22.1
    - bioconda:abricate=1.0.1
    - conda-forge:requests=2.25.1
    - conda-forge:geocoder=1.38
    - bioconda:perl-net-ssleay=1.85
    - bioconda:perl-libwww-perl=6.39
    - bioconda:perl-lwp-protocol-https=6.07
    - r-base=3.5.1
    - r-testit=0.11
    - r-argparse=2.0.1
    - r-ggplot2=3.3.0
    - r-scales=1.1.0
    - r-maps=3.3.0
    - entrez-direct=16.2
    - blast=2.9.0
    - r-taxize=0.9.95
    - mash=2.3
    - bioconda::perl-text-csv=2.00
    - r-dplyr=0.8.5
    - r-tidytext=0.2.4
    - r-stringr=1.4.0
    - tqdm=4.64.0
    - fuzzywuzzy=0.18.0
    - pronto=0.12.2
    - nltk=3.6.2
    - krona=2.8.1
