
###############################################################################
## General information
###############################################################################

version : "20231103" # version name of the new update
cores: 115
outdir: "../results/"

###############################################################################
## Data retrival
###############################################################################

#~~~~~~~~~~~~~~~
## NCBI
#~~~~~~~~~~~~~~~
eutils:
  ncbi_api_key: # Check
  email:  # Check
  query:
    plasmid:
      esearch_query: 'biomol_genomic[PROP] AND plasmid[FILT] AND bacteria[FILT] NOT complete cds[TITL] NOT gene[TITL] NOT genes[TITL] NOT contig[TITL] NOT scaffold[TITL] NOT whole genome map[TITL] NOT partial sequence[TITL] NOT (partial[Title] AND plasmid[TITL]) NOT locus[TITL] NOT region[TITL] NOT fragment[TITL] NOT integron[TITL] NOT transposon[TITL] NOT insertion sequence[TITL] NOT insertion element[TITL] NOT phage[TITL] NOT operon[TITL]'

#~~~~~~~~~~~~~~~
## PubMLST
#~~~~~~~~~~~~~~~
pmlst:
  db: "pubmlst_plasmid_seqdef"
  url: "http://rest.pubmlst.org" # Check
  url_schemes: "http://rest.pubmlst.org/db/pubmlst_plasmid_isolates/schemes" # Check
  cmd: "mlst --minid 85 --mincov 66 --scheme {scheme}"
  map:
    IncI1_: "IncI1__MLST"
    IncA/C: "IncA_C__PMLST"
    IncF: "IncF__RST"
    IncHI2: "IncHI2__DLST"
    IncN: "incN__MLST"
    IncHI1: "IncHI1__MLST"

rmlst:
  user: # Check
  passwd: # Check
  default_chrome_dw_dir:  # Check
  rmlst_ident: 100
  rmlst_cov: 100
  rmlst_header: ["qseqid", "qstart", "qend", "qlen", "sseqid", "sstart", "send", "slen", "stitle", "evalue", "pident", "length", "gaps"]
  rmlst_max_loci: 5
  nuccore_db_query: 'Bacteria[Organism] NOT plasmid [FILT] NOT complete cds[TITL] NOT gene[TITL] NOT genes[TITL] NOT contig[TITL] NOT scaffold[TITL] NOT whole genome map[TITL] NOT partial sequence[TITL] NOT locus[TITL] NOT region[TITL] NOT fragment[TITL] NOT integron[TITL] NOT transposon[TITL] NOT insertion sequence[TITL] NOT insertion element[TITL] NOT phage[TITL] NOT operon[TITL] NOT whole genome shotgun[TITL] NOT assembly[TITL]'
  nuccore_db_name : 'nuccore_local'
  blastn_header: ["qseqid", "qlen", "sseqid", "stitle", "slen", "evalue", "bitscore", "length", "gaps", "pident", "qcovs", "qcovhsp"]
  blastn_pident: 99
  blastn_qcovs: 80

#~~~~~~~~~~~~~~~
## ABRicate
#~~~~~~~~~~~~~~~
abricate:
  replace_getdb: True #Check_ use the getdb_bin file with the updated links
  getdb_bin: "../src/patch_abricate-get_db" #Check
  dbs: ["argannot", "card", "plasmidfinder", "resfinder", "vfdb"]
  params:
    argannot:
      ident: 95
      cov: 95
    card:
      ident: 95
      cov: 95
    plasmidfinder:
      ident: 80
      cov: 60
    resfinder:
      ident: 95
      cov: 95
    vfdb:
      ident: 95
      cov: 95

#~~~~~~~~~~~~~~~~~~~~~~~~~~~
## Human Disease Ontology
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
disease_ontology:
  url: "http://purl.obolibrary.org/obo/doid.obo"


###############################################################################
## Data processing
###############################################################################

filtering:
  dfilter: 'contig|\sgene(?!tic|ral|rat|ric)|integron|transposon|scaffold|insertion sequence|insertion element|phage|operon|partial sequence|partial plasmid|region|fragment|locus|complete (?!sequence|genome|plasmid|\.|,)|(?<!complete sequence, )whole genome shotgun|artificial|synthetic|vector'
  minlength : 744

blast:
  ext: ["nin", "nhr", "nsq"]

location_mapping:
  google_api: "AIzaSyCtJW88JUfJ3ZnmjyvpuBYRi25iB2mzERk" # Check
  mapping: "../src/locations_20231103.csv" # Check
  corrections: "../src/location_corrections_20231103.csv" # Check

host_mapping:
  file: "../src/hosts_20231103.csv" # Check
  regexes:
    env: "environment|seawater|freshwater|soil|sediment|tidal|water|\\bsink\\b|\\bpond\\b|\\bocean\\b|\\bsand\\b|\\briver\\b|\\bmud\\b|\\blake\\b|\\bsea\\b|\\bmarsh\\b|sludge|permafrost|\\bgrass\\b|\\bglacier\\b"
    bos_taurus: "\\bcow\\b|beef|cattle|bovine|calf"
    human: "human|girl|boy|children|infant|male|female|patient|people|person|baby|adult"
    mice: "mouse|mice"
    chicken: "chicken|hen|broiler|poultry"
    pig: "piglet|pork|\\bpig\\b|porcine|\\bswine\\b"
    two_words: "\\b\\w+\\s+\\w+\\b"
    patterns: "-|sp.| subsp$| cv$| l$|wild|meat|\\bpet\\b|plant|healthy|\\bsick\\b|\\bzoo\\b|ground|fermented|rhizoere|\\broot\\b|feces|\\braw\\b|\\bleaf\\b|\\bleaves\\b|\\bgut\\b|isolated from "

###############################################################################
## Data downstream
###############################################################################
previous_table:  # Check

mash:
  sketch_params: "-i -S 42 -p 20 -k 21 -s 1000"
  dist0_params: "-d 0 -p 20"
  distS_params: "-d 0.00123693 -p 20"
  dist_params: "-t -p 20"

krona:
  url: "https://github.com/marbl/Krona/archive/xl2.5.zip" # Check
  dir: "tools/KronaTools"

umap:
  neighbors: 50
  components: 2
  min_dist: 0.1
